apiVersion: apps/v1
kind: Deployment
metadata:
  name: ci-cd-node-app
  labels:
    app: ci-cd-node-app
spec:
  selector:
    matchLabels:
      app: ci-cd-node-app
  replicas: 1
  template:
    metadata:
      labels:
        app: ci-cd-node-app
    spec:
      containers:
        - name: ci-cd-node-app
          image: namanyash/sit737-ci-cd:tagversion
          ports:
            - containerPort: 5000
---
apiVersion: v1
kind: Service
metadata:
  name: ci-cd-node-app-service
  labels:
    app: ci-cd-node-app
spec:
  type: LoadBalancer
  ports:
    - port: 8000
      protocol: TCP
      targetPort: 5000
  selector:
    app: ci-cd-node-app
